version: '3'

services:

  dotnet_spark:
    container_name: dotnet-spark
    build: 
      context: ./docker-setup/dotnet-spark
      args:
        - DOTNET_CORE_VERSION=3.1
        - DOTNET_SPARK_VERSION=2.1.1
        - SPARK_VERSION=3.2.1
        - HADOOP_VERSION=2.7
    image: dotnet-spark:2.1.1-3.2.1
    ports: 
      - 5567:5567
    volumes:
      - ".:/workspace"